# Generated by Django 5.1.1 on 2024-09-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.annaandlucios.com/wp-content/uploads/2017/12/image_soon_large.jpg', max_length=500),
        ),
    ]
